---
# tasks file for rdiff-backup
# Installs rdiff-bakcup, librsync2 and dependencies
- name: rdiff-backup | install rdiff-backup
  become: true
  apt:
    update_cache: true
    name: rdiff-backup
    state: present

- name: rdiff-backup | create cron job
  become: true
  template:
    src: etc-crond-rdiff-backup.j2
    dest: /etc/cron.{{ rdiff_backup_frequency }}/rdiff-backup
    mode: 0755
