---
# tasks file for rdiff-backup

- name: rdiff-backup | install rdiff-backup
  become: true
  apt:
    update_cache: true
    name: rdiff-backup
    state: present

- name: rdiff-backup | create log directory
  become: true
  file:
    path: /var/log/rdiff-backup-data
    state: directory
    mode: 0755

- name: rdiff-backup | configure logrotate
  become: true
  template:
    backup: false
    dest: /etc/logrotate.d/rsyncd
    src: logrotated-rsyncd.j2
    mode: 0644
